repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      #- id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      # - id: no-commit-to-branch
      #   args:
      #     - --pattern=master|main
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/myint/autoflake
    rev: v2.1.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=105
          - --max-doc-length=90
          - --ignore=E203,W503
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args:
          - --line-length=105
          - .
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --line-length=105
          - --src=zoo_calrissian_runner
  # - repo: local
  #   hooks:
  #   -   id: pylint
  #       name: pylint
  #       entry: pylint
  #       language: system
  #       types: [python]
  #       require_serial: true
  #       args:
  #         - --disable=unused-argument
  #         - snapping
  #         - --disable=C0114,C0115,C0116,R0913
